### ISSUE TITLE
PIO2 fails to build on Summit with IBM XL compiler and -O3 in CFLAGS

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#215]
Steps to reproduce:
```
module load cmake
git clone https://github.com/E3SM-Project/ParallelIO.git
cd ParallelIO
mkdir build
cd build
CC=mpicc CXX=mpicxx FC=mpif90 cmake -DCMAKE_C_FLAGS:STRING="-O3" -DWITH_NETCDF=OFF -DPnetCDF_PATH="/autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-3/parallel-netcdf-1.8.1-mib5e6ivbcesgal3hvzvbwxso3dugyun" ..
make
```
The error mesage is:
```
[ 23%] Building C object src/clib/CMakeFiles/pioc.dir/pio_file.c.o
[ 23%] Building C object src/clib/CMakeFiles/pioc.dir/pioc_support.c.o
/sw/summit/xl/16.1.1-3/xlC/16.1.1/bin/.orig/xlc_r: error: 1501-230 Internal compiler error; please contact your Service Representative. For more information visit:
http://www.ibm.com/support/docview.wss?uid=swg21110810
make[2]: *** [src/clib/CMakeFiles/pioc.dir/pioc_support.c.o] Error 41
make[1]: *** [src/clib/CMakeFiles/pioc.dir/all] Error 2
make: *** [all] Error 2
```
This issue can cause E3SM cases to fail during phase build on Summit, as -O3 flag is always used for IBM compiler in non-DEBUG mode:
```
<compiler COMPILER="ibm">
  <CFLAGS>
    <base> -g -qfullpath -qmaxmem=-1 -qphsinfo </base>
    <append DEBUG="FALSE"> -O3  </append>
    ...
  </CFLAGS>
```

**Comment by dqwu** [comment]
Update: -O2 or -O1 flag has the same issue. -O0 works.
We might need to identify which code block inside pioc_support.c is not supported by IBM XL C compiler.

**Comment by dqwu** [comment]
@jayeshkrishna 
For E3SM production run commit 0cee902d9918a7864d18d1a151243c9673d00b8f still doe not work.

The reason is that "-qsmp=omp" is also in CMAKE_C_FLAGS, causing -qnoopt to be ignored
`/sw/summit/xl/16.1.1-3/xlC/16.1.1/bin/.orig/xlc_r: warning: 1501-264 The options qsmp and O0 are incompatible. Option O0 is ignored.`

Perhaps we need this change:
`set_source_files_properties(pioc_support.c PROPERTIES COMPILE_FLAGS "-qnoopt -qnosmp")`

**Comment by jayeshkrishna** [comment]
Does that change (set_source_files_properties(..."-qnoopt -qnosmp")) work with E3SM ?

**Comment by jayeshkrishna** [comment]
After investigating this issue further it looks like it wouldn't be easy to circumvent this XL compiler bug. One set of changes that were required to get pioc_support.c to compile with XL on Summit is available at jayeshkrishna/workaround_Summit_XL_bug

* Split the contents of pioc_support.c into three files (reduce the size of the source file)
* Remove some unused functions (reduce the size of the source file)
* Change logic of typecasting (int **) to (int *) when calling PIOc_get_var_int()

However why the above set of changes work is not clear. It would be unwise for us to chase this internal compiler error for now (since a simple source code change cannot circumvent this compiler bug).

So I think we should go ahead and merge the hack to turn off optimization for pioc_support.c (for Summit + XL) - jayeshkrishna/temp_XL_Summit_fix . @dqwu, any thoughts ?

**Comment by dqwu** [comment]
@jayeshkrishna 
I am OK with the workaround in jayeshkrishna/temp_XL_Summit_fix branch. The impact is minimal (only on Summit, only for XL compiler, only on a single source file). It is possible that a new version of XL compiler will fix this internal error when optimization is on for pioc_support.c
